name: CB-CD-ACTIONS-WORKFLOW

on:
  push:
    branches-ignore:
      - main
      - master

jobs:
  cb-env-job:
    name: CB-ENV-JOB
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: |
          echo "hello world..."
